//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admin_az
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cita()
        {
            this.facturas = new HashSet<factura>();
            this.trabajoes = new HashSet<trabajo>();
        }
    
        public int idcita { get; set; }
        public Nullable<int> idcliente { get; set; }
        public Nullable<int> idestado { get; set; }
        public Nullable<int> iduser { get; set; }
        public Nullable<int> idmetodo { get; set; }
        public Nullable<System.DateTime> fechaCita { get; set; }
        public double monto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> resta { get; set; }
        public string hora { get; set; }
        public string asunto { get; set; }
        public Nullable<double> montopagado { get; set; }
        public Nullable<bool> condicion { get; set; }
        public Nullable<int> artista { get; set; }
        public Nullable<int> oferta { get; set; }
        public string tiempo_estimado { get; set; }
    
        public virtual artista artista1 { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual estadocita estadocita { get; set; }
        public virtual metodoppago metodoppago { get; set; }
        public virtual oferta oferta1 { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trabajo> trabajoes { get; set; }
    }
}
