//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admin_az
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentacxp
    {
        public int idcuentacxp { get; set; }
        public string cliente { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public double monto { get; set; }
        public Nullable<int> idiente { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<int> idcita { get; set; }
    }
}
