//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admin_az
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentaCXC
    {
        public int idcxc { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string proveedor { get; set; }
        public Nullable<System.DateTime> fechaPago { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<bool> estado { get; set; }
        public string usuario { get; set; }
    }
}
