//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admin_az
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public int idfactura { get; set; }
        public int idusuer { get; set; }
        public Nullable<int> idcita { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idmetodo { get; set; }
    
        public virtual cita cita { get; set; }
        public virtual metodoppago metodoppago { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
