//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admin_az
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Cliente
    {
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int idcliente { get; set; }
        public string telefono { get; set; }
        public int idcita { get; set; }
        public Nullable<int> idestado { get; set; }
        public Nullable<System.DateTime> fechaCita { get; set; }
        public Nullable<int> iduser { get; set; }
        public Nullable<int> idmetodo { get; set; }
        public double monto { get; set; }
        public Nullable<double> resta { get; set; }
        public string hora { get; set; }
        public string estado { get; set; }
        public int estadoid { get; set; }
        public string codigo { get; set; }
        public int Expr1 { get; set; }
        public string metodo { get; set; }
        public Nullable<bool> condicion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> montopagado { get; set; }
    }
}
