//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admin_az
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1_usuario
    {
        public string nombre { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public string tipo { get; set; }
        public int idtipo { get; set; }
        public int iduser { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
