//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admin_az
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_reimprimir
    {
        public int idcita { get; set; }
        public int idmetodo { get; set; }
        public int iduser { get; set; }
        public Nullable<System.DateTime> fechaCita { get; set; }
        public double monto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> resta { get; set; }
        public string hora { get; set; }
        public int idcliente { get; set; }
        public string nombre { get; set; }
        public string metodoP { get; set; }
        public string nombreU { get; set; }
        public Nullable<double> montopagado { get; set; }
        public string tiempo_estimado { get; set; }
        public string apellido { get; set; }
        public string telefono { get; set; }
    }
}
